


make:
	rm ordena1 ; gcc -o ordena1 ordenacao.c -Wall -Wextra -pedantic 

exemplo:
	rm exemplo ; gcc -o exemplo sorting.c -Wall -Wextra -pedantic

create:
	rm exe ; gcc -o exe Entrad.c -I./gfx -L./gfx -lgfx -lSDL -lSDL_gfx -lSDL_ttf -Wall -Wextra -pedantic ; ./exe

clean:
	rm exe *~
