
make:
	rm exe ; gcc -o exe Arvore_Binaria.c -I./gfx -L./gfx -lgfx -lSDL -lSDL_gfx -lSDL_ttf -Wall -Wextra -pedantic ; ./exe

create:
	gcc -o exe Arvore_Binaria.c -I./gfx -L./gfx -lgfx -lSDL -lSDL_gfx -lSDL_ttf -Wall -Wextra -pedantic

clean:
	rm exe *~