
exemplo:
	gcc -o T T.c -I./gfx -L./gfx -lgfx -lSDL -lSDL_gfx -lSDL_ttf -Wall -Wextra -pedantic

clean:
	rm T *~

make t: 
	rm T ; gcc -o T T.c -I./gfx -L./gfx -lgfx -lSDL -lSDL_gfx -lSDL_ttf -Wall -Wextra -pedantic
