


make:
	rm exe ; gcc -o exe Alocação_encadeada.c -I./gfx -L./gfx -lgfx -lSDL -lSDL_gfx -lSDL_ttf -Wall -Wextra -pedantic ; ./exe

create:
	gcc -o exe draw.c -I./gfx -L./gfx -lgfx -lSDL -lSDL_gfx -lSDL_ttf -Wall -Wextra -pedantic

clean:
	rm exe *~
